In [1]:
import numpy as np

In [79]:
np.random.seed(42)

w = np.random.rand(5)
#w = w/w[np.argmin(w)]
w

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [80]:
A = np.fromfunction(lambda i, j: w[i] / w[j], (5,5), dtype=int)
A

array([[1.        , 0.39395654, 0.51167106, 0.62563236, 2.40061135],
       [2.53835106, 1.        , 1.29880079, 1.58807456, 6.09359435],
       [1.9543806 , 0.76994102, 1.        , 1.22272374, 4.69170825],
       [1.5983828 , 0.62969336, 0.81784623, 1.        , 3.83709589],
       [0.41656056, 0.16410676, 0.21314198, 0.26061376, 1.        ]])

In [81]:
A@w

array([1.87270059, 4.75357153, 3.65996971, 2.99329242, 0.7800932 ])

In [82]:
np.divide(A@w, w)

array([5., 5., 5., 5., 5.])